version: "3"

networks:
  app-tier:
    driver: bridge

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

services:
  booking-service:
    build: ./bookingservice
    ports:
      - 80:8080
    depends_on:
      - eureka-service
      - kafka
    networks:
      - app-tier
  payment-service:
    build: ./paymentservice
    ports:
      - 8083:8083
    depends_on:
      - eureka-service
      - kafka
    networks:
      - app-tier
  notification-service:
    build: ./notificationservice
    depends_on:
      - kafka
    networks:
      - app-tier
  eureka-service:
    build: ./eurekaserver
    ports:
      - 8762:8762
    networks:
      - app-tier
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      #- KAFKA_CFG_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    networks:
      - app-tier
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    volumes:
      - "zookeeper_data:/bitnami"
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-tier

